/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerNameRouteImport } from './routes/$playerName'
import { Route as IndexRouteImport } from './routes/index'

const PlayerNameRoute = PlayerNameRouteImport.update({
  id: '/$playerName',
  path: '/$playerName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$playerName': typeof PlayerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$playerName': typeof PlayerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$playerName': typeof PlayerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$playerName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$playerName'
  id: '__root__' | '/' | '/$playerName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerNameRoute: typeof PlayerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$playerName': {
      id: '/$playerName'
      path: '/$playerName'
      fullPath: '/$playerName'
      preLoaderRoute: typeof PlayerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerNameRoute: PlayerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
